### ISSUE TITLE
I test it with windows 10

### ISSUE THREAD

**Issue by SuselK** [eugeneglova/binance-trading-bot#16]
Hello Eugen...
I test it the bot "v.1.1.11" with windows 10 on my PC.
My PC have german time.

The windows-logfile:
------------------------------------------------------------------------------------------
[2020-12-11 09:47:23.033] [info] connect
[2020-12-11 09:47:23.041] [info] get data stream
[2020-12-11 09:47:27.206] [info] listenKey ********
[2020-12-11 09:47:48.777] [info] BTCUSDT SHORT START
[2020-12-11 09:47:50.037] [error] BTCUSDT SHORT create orders date range limit reached
[2020-12-11 09:49:50.056] [error] BTCUSDT SHORT create orders date range limit reached
....

What is wrong?

Best Regards
Susan

**Comment by eugeneglova** [comment]
@MeoncoSusan please open settings for btc short and at the botton you will find date pricker
set it to some dates like 2019 - 2022 years to make it work always
![image](https://user-images.githubusercontent.com/2828226/101889424-6f265c80-3bb0-11eb-88aa-9243cfcf0252.png)

**Comment by SuselK** [comment]
Hello Eugen...
many thanks. This works.

But now have i new Error:
-------------------------------------------------------------------
[2020-12-11 11:53:57.800] [info] BTCUSDT SHORT START
[2020-12-11 11:53:59.601] [info] BTCUSDT SHORT create orders by position timeout
[2020-12-11 11:54:00.210] [info] BTCUSDT SHORT cancel open orders ( 0 0 )

[2020-12-11 11:54:00.536] [info] BTCUSDT SHORT { price: 17744.98, topBookPrice: 17742.98 }
[2020-12-11 11:54:00.541] [info] BTCUSDT SHORT [
  { price: 17744.98, amount: -0.005, priceDiff: -40 },
  { price: 17784.98, amount: -0.005, priceDiff: -40 },
  { price: 17824.98, amount: -0.015, priceDiff: -100 },
  { price: 17924.98, amount: -0.045, priceDiff: -120 },
  { price: 18044.98, amount: -0.072, priceDiff: -160 },
  { price: 18204.98, amount: -0.116, priceDiff: -240 },
  { price: 18444.98, amount: -0.231, priceDiff: -240 }
]
[2020-12-11 11:54:00.546] [info] BTCUSDT SHORT create orders
[2020-12-11 11:54:00.910] [info] BTCUSDT SHORT
[2020-12-11 11:54:00.912] [error] Error
    at C:\Users\Mario Hauser\AppData\Local\Programs\binance-trading-bot\resources\app.asar\src\electron\bot.js:161:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-12-11 11:54:00.916] [error] {
  code: -4061,
  msg: "Order's position side does not match user's setting."
}

Best Regards
Susan

**Comment by eugeneglova** [comment]
you need to change position mode to `Hedge`
![image](https://user-images.githubusercontent.com/2828226/101895941-448cd180-3bb9-11eb-87f1-57bbce430ccb.png)

**Comment by SuselK** [comment]
Hello Eugen...
cool :-) Thank you

You are the best and your support is very fast!

Best Regards
Susan
